# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(790, 391)
        StartWindow.setStyleSheet("QMainWindow {\n"
"background-color: #464258;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, -10, 761, 171))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(72)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 243, 82);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(290, 160, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.start_button.setFont(font)
        self.start_button.setStyleSheet("background-color: rgb(113, 103, 153);\n"
"color: #fff352;\n"
"border-radius: 10px;")
        self.start_button.setObjectName("start_button")
        self.end_button = QtWidgets.QPushButton(self.centralwidget)
        self.end_button.setGeometry(QtCore.QRect(290, 220, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.end_button.setFont(font)
        self.end_button.setStyleSheet("background-color: #716799;\n"
"color: #fff352;\n"
"border-radius: 10px;")
        self.end_button.setObjectName("end_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 200, 35, 10))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 80, 201, 271))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("static/img/avatars/girl2.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, 60, 311, 301))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("static/img/avatars/girl_mirrored.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        StartWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "MainWindow"))
        self.label.setText(_translate("StartWindow", "MEMORY FIGHT"))
        self.start_button.setText(_translate("StartWindow", "LOAD GAME"))
        self.end_button.setText(_translate("StartWindow", "EXIT"))
